backend:
  name: git-gateway
  branch: main
  commit_messages:
    create: 'Create {{collection}} “{{slug}}”'
    update: 'Update {{collection}} “{{slug}}”'
    delete: 'Delete {{collection}} “{{slug}}”'
    uploadMedia: '[skip ci] Upload “{{path}}”'
    deleteMedia: '[skip ci] Delete “{{path}}”'

# Uncomment local_backend when you need to develop in your local
# local_backend: true # run npx netlify-cms-proxy-server for local testing

media_folder: static/assets
public_folder: /assets

collections:
  - name: posts # Used in routes, ie.: /admin/collections/:slug/edit
    label: Posts # Used in the UI
    label_singular: Post # Used in the UI, ie: "New Post"
    description: >
      Create awesome content here.
    folder: src/content/posts
    slug: '{{slug}}'
    summary: '{{title}} — {{year}}/{{month}}/{{day}}'
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - label: Template
        name: template
        widget: hidden
        default: BlogPostPage
      - label: Title
        name: title
        widget: string
        tagname: h1
      - label: Slug
        name: slug
        widget: string
        hint: Start slug with /. Use only alphanumeric characters, - and _. Avoid spaces in any cases.
      - label: Publish Date
        name: date
        widget: datetime
        dateFormat: YYYY-MM-DD
        timeFormat: HH:mm
        format: YYYY-MM-DD HH:mm
      - label: SEO Description
        name: description
        widget: text
      - label: Featured Image
        name: featuredImage
        widget: image
        required: false
        tagname: ''
      - label: Featured Image Caption
        name: featuredImageCaption
        widget: text
        required: false
      - label: Body
        name: body
        widget: markdown
        hint: Main content goes here.
  - label: Pages
    name: pages
    files:
      - label: Home
        name: home
        file: src/content/pages/index.md
        fields:
          - label: Template
            name: template
            widget: hidden
            default: HomePage
          - label: Slug
            name: slug
            widget: hidden
            default: /
          - label: Title
            name: title
            widget: string
          - label: Tagline
            name: tagline
            widget: string
          - label: Featured Image
            name: featuredImage
            widget: image
            required: false
          - label: 'Body'
            name: 'body'
            widget: 'markdown'
          - label: Skills
            name: skills
            widget: list
            summary: '{{name}}'
            fields:
              - name: icon
                label: Icon
                widget: image
                required: false
              - name: name
                label: Name
                widget: string
          - label: 'Experience'
            name: 'experience'
            widget: 'list'
            summary: '{{dateRange}}: {{jobTitle}}'
            fields:
              - name: 'dateRange'
                label: 'Date Range'
                widget: 'string'
              - name: 'jobTitle'
                label: 'Job Title'
                widget: 'string'
              - name: 'company'
                label: 'Company'
                widget: 'string'
              - name: 'description'
                label: 'Description'
                widget: 'string'
                required: false
              - name: 'location'
                label: 'Location'
                widget: 'string'
                required: false
          - label: 'Education'
            name: 'education'
            widget: 'list'
            summary: '{{school}} - {{fieldOfStudy}}'
            fields:
              - name: 'startYear'
                label: 'Start Year'
                widget: 'string'
              - name: 'endYear'
                label: 'End Year'
                widget: 'string'
              - name: 'school'
                label: 'School'
                widget: 'string'
              - name: 'fieldOfStudy'
                label: 'Field of Study'
                widget: 'string'
                required: false
              - name: 'grade'
                label: 'Grade'
                widget: 'string'
                required: false
              - name: 'location'
                label: 'Location'
                widget: 'string'
                required: false
          - label: Projects
            name: projects
            widget: list
            summary: '{{title}}'
            fields:
              - name: title
                label: Title
                widget: string
              - name: description
                label: Description
                widget: string
              - name: featuredImage
                label: Featured Image
                widget: image
              - name: demoUrl
                label: Demo URL
                widget: string
                required: false
              - name: sourceCodeUrl
                label: Source Code URL
                widget: string
                required: false
              - name: techStack
                label: Tech Stack
                widget: list
                required: true
                fields:
                  - name: name
                    label: Name
                    widget: string
          - label: 'CTA'
            name: 'cta'
            widget: 'object'
            fields:
              - name: 'ctaText'
                label: 'CTA text'
                widget: 'string'
              - name: 'ctaLink'
                label: 'CTA Link'
                widget: 'string'
  - name: settings
    label: Settings
    files:
      - name: general
        label: General
        file: 'src/util/site.json'
        fields:
          - label: meta
            name: meta
            widget: object
            fields:
              - widget: string
                name: title
                label: Site Title
                required: true
              - widget: string
                name: titleTemplate
                label: Title Template
                default: '%s'
                required: true
              - widget: string
                name: siteUrl
                label: Website URL
                required: true
              - widget: text
                name: description
                label: Description
                default: ''
                required: false
              - widget: image
                name: image
                label: image
                default: /assets/onderonur.jpg
              - widget: string
                name: twitterUsername
                label: Twitter
                required: false
              - widget: string
                name: linkedinUsername
                label: LinkedIn
                required: false
              - widget: string
                name: githubUsername
                label: GitHub
                required: false
              - widget: string
                name: mail
                label: Mail
                required: false
